### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by adrianhorning08** [adrianhorning08/vinyasa#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Smooth, bug-free navigation
- [x] Presentational Components
- [x] Styling
- [x] Adequate and appropriate seeds
- [x] Demo user signin?

**Comment by niartenyaw** [comment]
Looks great!

## Functionality

- [x] The `vinyasa` text at the top should link back to `/`
- [x] Have `https://vinyasa.herokuapp.com/#/vneorigbnoeirnboin` re-route to an appropriate URL
- [x] Errors should clear when moving from `login` to `signup` or vice-versa

## Styling

- [x] Would like to see the root page styled a bit more for this MVP, specifically the buttons and where they go on the page. Will the buttons be in a nav bar?

**Comment by niartenyaw** [comment]
Awesome, you can close!
